### ISSUE TITLE
Gazebo starting problem

### ISSUE THREAD

**Issue by shadynasrat** [Woojin-Seol/KVRC2022#2]
Gazebo lunched fine on the first try using "roslaunch khnp_competition gazebo.launch"

But on the second try gives this error "ERROR [ekf2] start failed (-1)"

**Comment by engcang** [comment]
Hi @shadynasrat .

Can you attach your `~/.bashrc` file here?
Did you install the right commit version of `PX4-SITL` with `lockstep` disabled as explained in here? - https://github.com/Woojin-Seol/KVRC2022#-requirements--installation (we are using `96c7fe4978bab2af970a097f4898e024c2d33440` commit version).

**Comment by Woojin-Seol** [comment]
A conflict with the unfinished gazebo server may be the problem.
Shut down 'gzserver' from 'System Monitoring' and try again.

**Comment by engcang** [comment]
@shadynasrat Any update of this issue?

**Comment by engcang** [comment]
I think this issue can be closed as there was no more further updates longer than one month. Closing the issue.
